import React, { useState } from 'react';
import { mergeModIds } from './commandlineUtils';
interface Mod { id: string; name: string; author?: string; thumbnailUrl?: string; }
export const ModSelector: React.FC<{ value: string; onChange: (value: string) => void }> = ({ value, onChange }) => {
  const [q, setQ] = useState(''); const [results, setResults] = useState<Mod[]>([]); const [page, setPage] = useState(1); const [more, setMore] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const ids = value.split(/[;,\s]+/).filter(Boolean);
  const search = async (p = 1) => { if (!q.trim()) return; setLoading(true); setError(''); try { const r = await fetch(`/api/mods/search?q=${encodeURIComponent(q)}&page=${p}&pageSize=12`); const b = await r.json(); if (!r.ok) throw new Error(b.error); setResults(p === 1 ? b.results : [...results, ...b.results]); setPage(p); setMore(Boolean(b.hasMore)); } catch (e: any) { setError(e.message || 'Search failed'); } finally { setLoading(false); } };
  return <div style={{ marginTop: 8, padding: 8, border: '1px solid #444', borderRadius: 4 }}><b>Select Mods</b><div style={{ display: 'flex', gap: 6, marginTop: 6 }}><input value={q} onChange={e => setQ(e.target.value)} placeholder="Search mods by name or ID" style={{ flex: 1 }} /><button type="button" onClick={() => search()} disabled={loading}>Search</button></div>{ids.length > 0 && <div style={{ marginTop: 6 }}>Selected: {ids.map(id => <button type="button" key={id} onClick={() => onChange(ids.filter(x => x.toLowerCase() !== id.toLowerCase()).join(','))} style={{ margin: 2 }}>{id} ×</button>)}</div>}{loading && <div>Searching…</div>}{error && <div style={{ color: '#f88' }}>{error} <button type="button" onClick={() => search(page)}>Retry</button></div>}{!loading && !error && q && !results.length && <div style={{ color: '#aaa' }}>No mods found.</div>}{results.map(m => <div key={m.id} style={{ display: 'flex', gap: 8, alignItems: 'center', marginTop: 6, background: '#181a20', padding: 5 }}>{m.thumbnailUrl && <img src={m.thumbnailUrl} width="32" height="32" alt="" />}<span style={{ flex: 1 }}><b>{m.name}</b><br /><small>{m.id} · {m.author || 'Unknown author'}</small></span><button type="button" onClick={() => onChange(mergeModIds(value, [m.id]))} disabled={ids.some(x => x.toLowerCase() === m.id.toLowerCase())}>Add</button></div>)}{more && <button type="button" onClick={() => search(page + 1)} disabled={loading}>Load more</button>}</div>;
};
